parameters:
#    iloweb_portfolio.example.class: Iloweb\PortfolioBundle\Example

services:
#    iloweb_portfolio.example:
#        class: %iloweb_portfolio.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
