IlowebPortfolioBundle:
    resource: "@IlowebPortfolioBundle/Resources/config/routing.yml"
    prefix:   /iloweb

SdzBlogBundle:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
