sdzblog:
  pattern: /{page}
  defaults: { _controlleur: SdzBlogBundle:Blog:liste, page: 1 }
  requirements:
    page: \d+
    
sdzblog_voir:
  pattern:  /{slug}
  defaults: { _controller: SdzBlogBundle:Blog:voir }
  
sdzblog_ajouter:
  pattern:  /ajouter/article
  defaults: { _controller: SdzBlogBundle:Blog:ajouter }
  
sdzblog_modifier:
  pattern:  /modifier/{id}
  defaults: { _controller: SdzBlogBundle:Blog:modifier }
  requirements:
    id: \d+
    
sdzblog_supprimer:
  pattern : /supprimer/{id}
  defaults: { _controller: SdzBlogBundle:Blog:supprimer }
  requirements:
    id: \d+
HelloTheWorld:
    pattern:  /hello-world
    defaults: { _controller: SdzBlogBundle:Blog:index }

voir_article:
    pattern:  /{id}
    defaults: { _controller: SdzBlogBundle:Blog:voir }
    
voir_article_slug:
  pattern:  /{annee}/{slug}.{format}
  defaults: { _controller: SdzBlogBundle:Blog:voirSlug, format: html }
  requirements:
    annee:  \d{4}
    format: html|xml